language: go
go:
  - 1.7
gobuild_args: -x --ldflags "-X 'main.VERSION=$TRAVIS_TAG commit $TRAVIS_COMMIT'"

script: echo "Deploy only, tested on own gitlab becouse travis incoming connect restrictions."

before_deploy:
  - mkdir release
  - 'GOARCH=386 GOOS=linux go build -o lets-proxy; tar -zcf release/lets-proxy-linux-i386.tar.gz lets-proxy'
  - 'GOARCH=amd64 GOOS=linux go build -o lets-proxy; tar -zcf release/lets-proxy-linux-amd64.tar.gz lets-proxy'
  - 'GOARCH=386 GOOS=freebsd go build -o lets-proxy; tar -zcf release/lets-proxy-freebsd-i386.tar.gz lets-proxy'
  - 'GOARCH=amd64 GOOS=freebsd go build -o lets-proxy; tar -zcf release/lets-proxy-freebsd-amd64.tar.gz lets-proxy'
  - 'GOARCH=386 GOOS=windows go build -o lets-proxy.exe; zip release/lets-proxy-windows-i386.zip lets-proxy.exe'
  - 'GOARCH=amd64 GOOS=windows go build -o lets-proxy.exe; zip release/lets-proxy-windows-amd64.zip lets-proxy.exe'

deploy:
  skip_cleanup: true
  tags: true
  provider: releases
  on:
    repo: rekby/lets-proxy
    tags: true
  go: 1.7
  api_key:
    secure: AUR6257+ZDxMulgJDUvRbEZjN802urZli7nCcJesL1VIoFSiwwDagzV/n8ws/uqdAmi+kdU9rb4bDeQQbpON3WJZAonR7IdiljVuThKgodYpzYEUNk56DQN4Cru8e53FL0jwhfDGXzm0sr5w82tKMdhCCPcYZwvAMouzw7GLNHnX4geWlANf4Sk779AOoQim7kz907L74EU86yyyJ788O/ms1xPAk1OI7leg4nh8UGxje88/N+1FHRiQyfN7fJfqRYPigdb/BpIGfRAyXvMNRURZw/Hoi3TH6SCm+EQSM8HygDu1+OGSupa/+pxMLbXksqlZ+o9Uq2gLYOm+/mMZIn9p2P54uzGBdxcdJfjUFAVmY+BoiL3qFHQhaxSXNvHmtgx1QeQYexfvm7NLB7vlDFDZcp/H3MaiGOxYI2eQ3FW8rCq0hYNj5tcVBkFoIwtRXwjuTOEYZGQw2muQ2F0IxTyic5VqDMh7qtc3eDk8TCtDlsjEv28mhypyEL7N5LQnQG67YGmdBZqp1dSRKf0Q5fSjygmCCVyTcir5mMnYxA7CuikePBMhzFFpkdxEJhdzsVNSp9vfisBBJ20tSlrUQ9MmnJCnV4FylY1VY3KVM/BA6iF1l2zpO5WlZSpRa4ehW0mBHgBAUsWGa9Y0vY7wVrU8o9Mv1On6yY2fdiA/sUg=
  file:
    - "release/lets-proxy-linux-i386.tar.gz"
    - "release/lets-proxy-linux-amd64.tar.gz"
    - "release/lets-proxy-freebsd-i386.tar.gz"
    - "release/lets-proxy-freebsd-amd64.tar.gz"
    - "release/lets-proxy-windows-i386.zip"
    - "release/lets-proxy-windows-amd64.zip"
