language: go
go:
  - 1.7
gobuild_args: --ldflags "-X \"main.VERSION=$TRAVIS_TAG commit $TRAVIS_COMMIT\""

script: echo "Deploy only, tested on own gitlab becouse travis incoming connect restrictions."

before_deploy:
  - mkdir release
  - 'GOARCH=386 GOOS=linux go build --ldflags "-X \"main.VERSION=$TRAVIS_TAG commit $TRAVIS_COMMIT\"" -o lets-proxy; tar -zcf release/lets-proxy-linux-i386.tar.gz lets-proxy'
  - 'GOARCH=amd64 GOOS=linux go build --ldflags "-X \"main.VERSION=$TRAVIS_TAG commit $TRAVIS_COMMIT\"" -o lets-proxy; tar -zcf release/lets-proxy-linux-amd64.tar.gz lets-proxy'
  - 'GOARCH=386 GOOS=freebsd go build --ldflags "-X \"main.VERSION=$TRAVIS_TAG commit $TRAVIS_COMMIT\"" -o lets-proxy; tar -zcf release/lets-proxy-freebsd-i386.tar.gz lets-proxy'
  - 'GOARCH=amd64 GOOS=freebsd go build --ldflags "-X \"main.VERSION=$TRAVIS_TAG commit $TRAVIS_COMMIT\"" -o lets-proxy; tar -zcf release/lets-proxy-freebsd-amd64.tar.gz lets-proxy'
  - 'GOARCH=386 GOOS=windows go build --ldflags "-X \"main.VERSION=$TRAVIS_TAG commit $TRAVIS_COMMIT\"" -o lets-proxy.exe; zip release/lets-proxy-windows-i386.zip lets-proxy.exe'
  - 'GOARCH=amd64 GOOS=windows go build --ldflags "-X \"main.VERSION=$TRAVIS_TAG commit $TRAVIS_COMMIT\"" -o lets-proxy.exe; zip release/lets-proxy-windows-amd64.zip lets-proxy.exe'

deploy:
  skip_cleanup: true
  tags: true
  provider: releases
  on:
    repo: rekby/lets-proxy
    tags: true
  go: 1.7
  api_key: $GITHUB_TOKEN
  file:
    - "release/lets-proxy-linux-i386.tar.gz"
    - "release/lets-proxy-linux-amd64.tar.gz"
    - "release/lets-proxy-freebsd-i386.tar.gz"
    - "release/lets-proxy-freebsd-amd64.tar.gz"
    - "release/lets-proxy-windows-i386.zip"
    - "release/lets-proxy-windows-amd64.zip"
